//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountValidationRecovery
    {
        public string Id { get; set; }
        public System.DateTime InsertionTimeStamp { get; set; }
        public System.DateTime ExpirationTime { get; set; }
        public Nullable<System.DateTime> ValidationTimeStamp { get; set; }
        public long UserId { get; set; }
    
        public virtual AccountUser AccountUser { get; set; }
    }
}
