//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPassword
    {
        public long UserId { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }
        public int Iterations { get; set; }
        public int Attempts { get; set; }
        public Nullable<System.DateTime> AttemptTimeStamp { get; set; }
    
        public virtual AccountUser AccountUser { get; set; }
    }
}
