//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomePending
    {
        public int incomeId { get; set; }
        public int id { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> waytopayId { get; set; }
    
        public virtual Income Income { get; set; }
        public virtual Waytopay Waytopay { get; set; }
    }
}
