//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waytopay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Waytopay()
        {
            this.PaymentPending = new HashSet<PaymentPending>();
            this.IncomePending = new HashSet<IncomePending>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool disabled { get; set; }
        public Nullable<int> typeId { get; set; }
    
        public virtual WaytopayType WaytopayType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentPending> PaymentPending { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomePending> IncomePending { get; set; }
    }
}
